pin_map = {
    "CON1-P01": {
        "Type": "Power",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P02": {
        "Type": "Power",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P03": {
        "Type": "Digital I/O, I2C SDA",
        "Capabilities": ["digital_read", "digital_write", "i2c"],
        "Capabilities Senors": ["I2C-compatible sensors"],
        "Example Data Feeds": ["Data from I2C devices"],
    },
    "CON1-P04": {
        "Type": "Power",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P05": {
        "Type": "Digital I/O, I2C SCL",
        "Capabilities": ["digital_read", "digital_write", "i2c"],
        "Capabilities Senors": ["I2C-compatible sensors"],
        "Example Data Feeds": ["Data from I2C devices"],
    },
    "CON1-P06": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P07": {
        "Type": "Digital I/O, SDIO CMD",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data from SDIO devices"],
    },
    "CON1-P08": {
        "Type": "Digital I/O, UART TX",
        "Capabilities": ["digital_read", "digital_write", "serial_write"],
        "Capabilities Senors": ["UART-compatible sensors"],
        "Example Data Feeds": ["Serial data output"],
    },
    "CON1-P09": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P10": {
        "Type": "Digital I/O, UART RX",
        "Capabilities": ["digital_read", "serial_read"],
        "Capabilities Senors": ["UART-compatible sensors"],
        "Example Data Feeds": ["Serial data input"],
    },
    "CON1-P11": {
        "Type": "Digital I/O, SDIO D3",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data from SDIO devices"],
    },
    "CON1-P12": {
        "Type": "Digital I/O, TDMB SCLK",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Clock signal for TDMB"],
    },
    "CON1-P13": {
        "Type": "Digital I/O, SDIO CLK",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Clock signal for SDIO devices"],
    },
    "CON1-P14": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P15": {
        "Type": "Digital I/O, PWM F",
        "Capabilities": ["digital_write", "pwm"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["PWM signals"],
    },
    "CON1-P16": {
        "Type": "Digital I/O, SDIO D0",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data from SDIO devices"],
    },
    "CON1-P17": {
        "Type": "Power",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P18": {
        "Type": "Digital I/O, SDIO D1",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data from SDIO devices"],
    },
    "CON1-P19": {
        "Type": "Digital I/O, PCM DIN",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data from PCM interface"],
    },
    "CON1-P20": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P21": {
        "Type": "Digital I/O, PCM DOUT",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data to PCM interface"],
    },
    "CON1-P22": {
        "Type": "Digital I/O, SDIO D2",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data from SDIO devices"],
    },
    "CON1-P23": {
        "Type": "Digital I/O, PCM CLK",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Clock signal for PCM"],
    },
    "CON1-P24": {
        "Type": "Digital I/O, PCM SYNC",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Synchronization signal for PCM"],
    },
    "CON1-P25": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P26": {
        "Type": "Digital I/O, PWM E",
        "Capabilities": ["digital_write", "pwm"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["PWM signals"],
    },
    "CON1-P27": {
        "Type": "Digital I/O, I2C M3 SDA",
        "Capabilities": ["digital_read", "digital_write", "i2c"],
        "Capabilities Senors": ["I2C-compatible sensors"],
        "Example Data Feeds": ["Data from I2C devices"],
    },
    "CON1-P28": {
        "Type": "Digital I/O, I2C M3 SCL",
        "Capabilities": ["digital_read", "digital_write", "i2c"],
        "Capabilities Senors": ["I2C-compatible sensors"],
        "Example Data Feeds": ["Data from I2C devices"],
    },
    "CON1-P29": {
        "Type": "Digital I/O, UART CTS",
        "Capabilities": ["digital_read", "serial_read"],
        "Capabilities Senors": ["UART-compatible sensors"],
        "Example Data Feeds": ["Clear to send signals for UART"],
    },
    "CON1-P30": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P31": {
        "Type": "Digital I/O, UART RTS",
        "Capabilities": ["digital_write", "serial_write"],
        "Capabilities Senors": ["UART-compatible sensors"],
        "Example Data Feeds": ["Request to send signals for UART"],
    },
    "CON1-P32": {
        "Type": "Digital I/O, PWM B",
        "Capabilities": ["digital_write", "pwm"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["PWM signals"],
    },
    "CON1-P33": {
        "Type": "Digital I/O, PWM A",
        "Capabilities": ["digital_write", "pwm"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["PWM signals"],
    },
    "CON1-P34": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P35": {
        "Type": "Digital I/O, TDMB FS",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Frame sync for TDMB"],
    },
    "CON1-P36": {
        "Type": "Digital I/O, SPDIF IN",
        "Capabilities": ["digital_read"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Digital audio input"],
    },
    "CON1-P37": {
        "Type": "Digital I/O, I2S MCLK",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Master clock for I2S"],
    },
    "CON1-P38": {
        "Type": "Digital I/O, TDMB DIN",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data input for TDMB"],
    },
    "CON1-P39": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON1-P40": {
        "Type": "Digital I/O, TDMB DOUT",
        "Capabilities": ["digital_read", "digital_write"],
        "Capabilities Senors": [],
        "Example Data Feeds": ["Data output for TDMB"],
    },
    "CON2-P1": {
        "Type": "Ground",
        "Capabilities": [],
        "Capabilities Senors": [],
        "Example Data Feeds": [],
    },
    "CON2-P2": {
        "Type": "Digital I/O, UART RX",
        "Capabilities": ["digital_read", "serial_read"],
        "Capabilities Senors": ["UART-compatible sensors"],
        "Example Data Feeds": ["Serial data input"],
    },
    "CON2-P3": {
        "Type": "Digital I/O, UART TX",
        "Capabilities": ["digital_write", "serial_write"],
        "Capabilities Senors": ["UART-compatible sensors"],
        "Example Data Feeds": ["Serial data output"],
    },
}
